#!/bin/bash

set -euo pipefail

CONFIG="${1:-}"

if [[ -z "$CONFIG" ]]; then
    echo "Usage: bash QC_make_multiqc_custom_content.sh path/to/config.sh"
    exit 1
fi

if [[ ! -f "$CONFIG" ]]; then
    echo "ERROR: Config file not found: $CONFIG"
    exit 1
fi

source "$CONFIG"

: "${OUTDIR:?ERROR: OUTDIR not set in config}"

CUSTOM_MQC_DIR="${OUTDIR}/multiqc/custom_content"
mkdir -p "$CUSTOM_MQC_DIR"

# Clear old custom content so removed sections do not keep showing up
find "$CUSTOM_MQC_DIR" -type f -delete 2>/dev/null || true

echo "Creating MultiQC custom content..."
echo "Custom content folder: $CUSTOM_MQC_DIR"

module purge
module load Anaconda3/2024.06-1

python - "$OUTDIR" "$CUSTOM_MQC_DIR" <<'PY'
import sys
import os
import glob
import pandas as pd
import math
import matplotlib.pyplot as plt

outdir = sys.argv[1]
custom_dir = sys.argv[2]

os.makedirs(custom_dir, exist_ok=True)

def read_tsvs(pattern):
    files = glob.glob(pattern, recursive=True)
    dfs = []

    for f in files:
        try:
            df = pd.read_csv(f, sep="\t")
            if not df.empty:
                dfs.append(df)
        except Exception as e:
            print(f"WARNING: could not read {f}: {e}")

    if dfs:
        return pd.concat(dfs, ignore_index=True)

    return pd.DataFrame()

def safe_num(x):
    if pd.isna(x):
        return None

    if isinstance(x, str):
        y = x.replace("%", "").strip()

        try:
            return float(y)
        except Exception:
            return x

    try:
        if math.isnan(float(x)):
            return None
    except Exception:
        pass

    return x

def df_to_mqc_yaml(df, out_yaml, section_id, section_name, description):
    if df.empty:
        print(f"Skipping empty section: {section_name}")
        return

    df = df.copy()

    if "sample" not in df.columns:
        print(f"Skipping {section_name}: no sample column")
        return

    data = {}

    for _, row in df.iterrows():
        sample = str(row["sample"])
        vals = {}

        for col in df.columns:
            if col == "sample":
                continue

            vals[str(col)] = safe_num(row[col])

        data[sample] = vals

    with open(out_yaml, "w") as out:
        out.write(f'id: "{section_id}"\n')
        out.write(f'section_name: "{section_name}"\n')
        out.write(f'description: "{description}"\n')
        out.write('plot_type: "table"\n')
        out.write("pconfig:\n")
        out.write(f'  id: "{section_id}_table"\n')
        out.write(f'  title: "{section_name}"\n')
        out.write("data:\n")

        for sample, vals in data.items():
            out.write(f'  "{sample}":\n')

            for k, v in vals.items():
                if v is None:
                    out.write(f'    "{k}": null\n')
                elif isinstance(v, (int, float)):
                    out.write(f'    "{k}": {v}\n')
                else:
                    vv = str(v).replace('"', '\\"')
                    out.write(f'    "{k}": "{vv}"\n')

    print(f"Wrote: {out_yaml}")

# -----------------------------
# Custom tables to include
# -----------------------------

mapping = read_tsvs(os.path.join(outdir, "mapping", "**", "*.mapping_summary.tsv"))
df_to_mqc_yaml(
    mapping,
    os.path.join(custom_dir, "custom_mapping_summary_mqc.yaml"),
    "custom_mapping_summary",
    "Custom Mapping Summary",
    "Mapping metrics parsed from STAR Log.final.out by the QC pipeline."
)

splice = read_tsvs(os.path.join(outdir, "splice_junctions", "**", "*.splice_junction_summary.tsv"))
df_to_mqc_yaml(
    splice,
    os.path.join(custom_dir, "custom_splice_junction_summary_mqc.yaml"),
    "custom_splice_junction_summary",
    "Splice Junction Summary",
    "STAR SJ.out.tab-derived splice junction summary, including annotated and novel junction fractions."
)

fastqc = read_tsvs(os.path.join(outdir, "fastqc", "**", "*.fastqc_parsed_metrics.tsv"))
df_to_mqc_yaml(
    fastqc,
    os.path.join(custom_dir, "custom_fastqc_parsed_metrics_mqc.yaml"),
    "custom_fastqc_parsed_metrics",
    "Custom FastQC Parsed Metrics",
    "Extra FastQC metrics parsed by the QC pipeline, including last-10-bp quality, GC peak, and maximum adapter percentage."
)

frag = read_tsvs(os.path.join(outdir, "fragment_size", "**", "*.fragment_size_summary.tsv"))
df_to_mqc_yaml(
    frag,
    os.path.join(custom_dir, "custom_fragment_size_summary_mqc.yaml"),
    "custom_fragment_size_summary",
    "Fragment Size Summary",
    "Fragment size summary metrics generated by the QC pipeline. Paired-end only."
)

# -----------------------------
# Dropoff compact summary table
# -----------------------------

drop_files = glob.glob(
    os.path.join(outdir, "dropoff", "**", "*.dropoff_profile.tsv"),
    recursive=True
)

drop_rows = []

for f in drop_files:
    try:
        sample = os.path.basename(f).replace(".dropoff_profile.tsv", "")
        df = pd.read_csv(f, sep="\t")

        exon_mean = df.loc[df["dist_mid"] < 0, "norm_count"].mean()
        intron_mean = df.loc[df["dist_mid"] > 0, "norm_count"].mean()

        near_exon = df.loc[df["dist_mid"] == -25.0, "norm_count"]
        near_intron = df.loc[df["dist_mid"] == 25.0, "norm_count"]

        near_exon_val = near_exon.iloc[0] if len(near_exon) else None
        near_intron_val = near_intron.iloc[0] if len(near_intron) else None

        ratio = None

        if near_exon_val is not None and near_exon_val != 0 and near_intron_val is not None:
            ratio = near_intron_val / near_exon_val

        drop_rows.append({
            "sample": sample,
            "dropoff_exon_side_mean_norm": exon_mean,
            "dropoff_intron_side_mean_norm": intron_mean,
            "dropoff_near_exon_-25bp_norm": near_exon_val,
            "dropoff_near_intron_25bp_norm": near_intron_val,
            "dropoff_near_intron_to_exon_ratio": ratio,
        })

    except Exception as e:
        print(f"WARNING: could not summarize dropoff file {f}: {e}")

drop_summary = pd.DataFrame(drop_rows)

if not drop_summary.empty:
    drop_summary.to_csv(
        os.path.join(custom_dir, "dropoff_compact_summary.tsv"),
        sep="\t",
        index=False
    )

df_to_mqc_yaml(
    drop_summary,
    os.path.join(custom_dir, "custom_exon_intron_dropoff_summary_mqc.yaml"),
    "custom_exon_intron_dropoff_summary",
    "Exon-Intron Drop-off Summary",
    "Compact summary of exon-intron boundary drop-off profiles. Full TSVs are staged beside the report."
)

# -----------------------------
# Combined dropoff plot
# -----------------------------

if drop_files:
    n = len(drop_files)
    fig_height = max(3, 2.8 * n)

    fig, axes = plt.subplots(
        nrows=n,
        ncols=1,
        figsize=(7, fig_height),
        sharex=True
    )

    if n == 1:
        axes = [axes]

    for ax, f in zip(axes, sorted(drop_files)):
        sample = os.path.basename(f).replace(".dropoff_profile.tsv", "")

        try:
            df = pd.read_csv(f, sep="\t")
            df = df.sort_values("dist_mid")

            ax.plot(
                df["dist_mid"],
                df["norm_count"],
                marker="o"
            )

            ax.axvline(
                0,
                linestyle="--"
            )

            # Force y-axis to start at 0 and end at sample-specific max + 5% padding
            ymax = df["norm_count"].max()

            if pd.isna(ymax) or ymax <= 0:
                ymax = 1.0

            ax.set_ylim(0, ymax * 1.05)

            ax.set_title(sample)
            ax.set_ylabel("Norm. count")

        except Exception as e:
            ax.set_title(f"{sample} - failed to plot")
            ax.set_ylim(0, 1)
            ax.text(
                0.5,
                0.5,
                str(e),
                transform=ax.transAxes,
                ha="center",
                va="center"
            )

    axes[-1].set_xlabel("Distance from exon-intron boundary (bp)")

    fig.suptitle("Exon-Intron Drop-off Profiles", y=0.995)
    fig.tight_layout()

    out_png = os.path.join(custom_dir, "exon_intron_dropoff_profiles_mqc.png")
    fig.savefig(out_png, dpi=200)
    plt.close(fig)

    print(f"Wrote combined dropoff image: {out_png}")
else:
    print("No dropoff profile TSVs found; skipping combined dropoff plot.")

# -----------------------------
# Combined fragment size plot
# -----------------------------

frag_plot_files = glob.glob(
    os.path.join(outdir, "fragment_size", "**", "*.fragment_size_hist.png"),
    recursive=True
)

if frag_plot_files:
    n = len(frag_plot_files)
    fig_height = max(3, 2.8 * n)

    fig, axes = plt.subplots(
        nrows=n,
        ncols=1,
        figsize=(7, fig_height)
    )

    if n == 1:
        axes = [axes]

    for ax, png in zip(axes, sorted(frag_plot_files)):
        sample = os.path.basename(png).replace(".fragment_size_hist.png", "")

        try:
            img = plt.imread(png)
            ax.imshow(img)
            ax.axis("off")
            ax.set_title(sample)

        except Exception as e:
            ax.axis("off")
            ax.set_title(f"{sample} - failed to load")
            ax.text(
                0.5,
                0.5,
                str(e),
                transform=ax.transAxes,
                ha="center",
                va="center"
            )

    fig.suptitle("Fragment Size Histograms", y=0.995)
    fig.tight_layout()

    out_png = os.path.join(custom_dir, "fragment_size_histograms_mqc.png")
    fig.savefig(out_png, dpi=200)
    plt.close(fig)

    print(f"Wrote combined fragment size image: {out_png}")
else:
    print("No fragment size histogram PNGs found; skipping combined fragment size plot.")

print("Done creating MultiQC custom content.")
PY

echo "Custom MultiQC content created in:"
echo "$CUSTOM_MQC_DIR"